apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-k8s-piny940-com-v1alpha1-provider
    failurePolicy: Fail
    name: mprovider.kb.io
    rules:
      - apiGroups:
          - k8s.piny940.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - providers
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-k8s-piny940-com-v1alpha1-provider
    failurePolicy: Fail
    name: vprovider.kb.io
    rules:
      - apiGroups:
          - k8s.piny940.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - providers
    sideEffects: None
