apiVersion: k8s.piny940.com/v1alpha1
kind: WorkloadIdentity
metadata:
  labels:
    app.kubernetes.io/name: kwimount
    app.kubernetes.io/managed-by: kustomize
  name: workloadidentity-sample
spec:

# TODO(user): Add fields here
